version: "1"
services:
  front_end:
    container_name: front_end
    build: 
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm start
  back_end:
    container_name: back_end
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: npm start
